$ANSIBLE_VAULT;1.1;AES256
35383138333937313861663862333434343035623039643861313761646136663632613734316162
3866636633333766383139663130346133373062333630320a653035623331306235383735623261
62666631626139356434646132353565626562333763306430383836653638353261373936336632
3632653662666636610a353961366633666232373633653934396366346563653665336161313561
34323663303338376337333737366566646264363732383464353636323132303234363738366233
38386631313563383138653930653731643031616365336638633338353563313866333630363838
37356535613734373934636463373131666436306561343939326433313438343534663839663061
65643161356132316231313163656237383535666262353432366464366563653938373336613562
38303735343836303739646538303861393637643733663536333366623935626132343731646464
3134666663343430373761323837353634663837396533623138
